name: Update formula

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package & formula name'
        required: true
        type: string
      version:
        description: 'Package version'
        required: true
        type: string

  workflow_call:
    inputs:
      package:
        description: 'Package & formula name'
        required: true
        type: string
      version:
        description: 'Package version'
        required: true
        type: string

jobs:
  update-formula:
    name: Update formula definition with new version
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update formula definition and commit the result
      run: |
        ./.github/scripts/update_formula.sh ${{ github.event.inputs.package }} ${{ github.event.inputs.version }}
        git config user.name 'GitHub Actions'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add Formula/apify-cli.rb
        git commit -m "Updating \`${{ github.event.inputs.package }}\` to version \`${{ github.event.inputs.version }}\`"
        git push
